// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+devtools@2.7.0_vite@6.4.1_@types+node@20.19.30_jiti@2.6.1_lightningcss@1.31.1_ter_f18c7afee45c6a07b67304ccd0c27d6b/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+devtools@2.7.0_vite@6.4.1_@types+node@20.19.30_jiti@2.6.1_lightningcss@1.31.1_ter_f18c7afee45c6a07b67304ccd0c27d6b/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../src/runtime/plugins/default-template")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.6_@types+node@20.19.30_cac@6.7.14_db0@0.3.4_ioredis@5.9_bcb9828f51a29e7b0a9054c71d12fac0/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
